// -------------Local URL
export const apiBaseUrl = `http://localhost:54790`;


export const baseUrl = ``;

// -------------live url
// export const apiBaseUrl =
//   `https://roshanbags.com/EcommerceAPI` || process.env.REACT_APP_BASE_URL;


export const gstRegex = /^(?:[0-3|9][0-9])[a-zA-Z0-9]{13}$/;
export const mobileRegex = /^\d{10}$/;
export const checkPhoneNumberValidation = (value) => {
  return mobileRegex.test(value);
};
// export const gstRegex = /^[0-9]{2}[a-zA-z0-9]{13}$/;

export const genderOption = [
  {
    key: 1,
    label: "Male",
    value: "Male",
  },
  {
    key: 2,
    label: "Female",
    value: "Female",
  },
  {
    key: 3,
    label: "Others",
    value: "Others",
  },
];

export const cityOptions = [
  { key: 1, label: "Delhi", value: "Delhi" },
  { key: 2, label: "Mumbai", value: "Mumbai" },
  { key: 3, label: "Kolkata", value: "Kolkata" },
  { key: 4, label: "Bengaluru", value: "Bengaluru" },
  { key: 5, label: "Chennai", value: "Chennai" },
  { key: 6, label: "Hyderabad", value: "Hyderabad" },
  { key: 7, label: "Pune", value: "Pune" },
  { key: 8, label: "Ahmedabad", value: "Ahmedabad" },
  { key: 9, label: "Surat", value: "Surat" },
  { key: 10, label: "Lucknow", value: "Lucknow" },
  { key: 11, label: "Jaipur", value: "Jaipur" },
  { key: 12, label: "Kanpur", value: "Kanpur" },
  { key: 13, label: "Mirzapur", value: "Mirzapur" },
  { key: 14, label: "Nagpur", value: "Nagpur" },
  { key: 15, label: "Ghaziabad", value: "Ghaziabad" },
  { key: 16, label: "Supaul", value: "Supaul" },
  { key: 17, label: "Vadodara", value: "Vadodara" },
  { key: 18, label: "Rajkot", value: "Rajkot" },
  { key: 19, label: "Visakhapatnam", value: "Visakhapatnam" },
  { key: 20, label: "Indore", value: "Indore" },
  { key: 21, label: "Thane", value: "Thane" },
  { key: 22, label: "Bhopal", value: "Bhopal" },
  { key: 23, label: "Pimpri-Chinchwad", value: "Pimpri-Chinchwad" },
  { key: 24, label: "Patna", value: "Patna" },
  { key: 25, label: "Bilaspur", value: "Bilaspur" },
  { key: 26, label: "Ludhiana", value: "Ludhiana" },
  { key: 27, label: "Agra", value: "Agra" },
  { key: 28, label: "Madurai", value: "Madurai" },
  { key: 29, label: "Jamshedpur", value: "Jamshedpur" },
  { key: 30, label: "Prayagraj", value: "Prayagraj" },
  { key: 31, label: "Nashik", value: "Nashik" },
  { key: 32, label: "Faridabad", value: "Faridabad" },
  { key: 33, label: "Meerut", value: "Meerut" },
  { key: 34, label: "Jabalpur", value: "Jabalpur" },
  { key: 35, label: "Kalyan", value: "Kalyan" },
  { key: 36, label: "Vasai-Virar", value: "Vasai-Virar" },
  { key: 37, label: "Najafgarh", value: "Najafgarh" },
  { key: 38, label: "Varanasi", value: "Varanasi" },
  { key: 39, label: "Srinagar", value: "Srinagar" },
  { key: 40, label: "Aurangabad", value: "Aurangabad" },
  { key: 41, label: "Dhanbad", value: "Dhanbad" },
  { key: 42, label: "Amritsar", value: "Amritsar" },
  { key: 43, label: "Aligarh", value: "Aligarh" },
  { key: 44, label: "Guwahati", value: "Guwahati" },
  { key: 45, label: "Howrah", value: "Howrah" },
  { key: 46, label: "Ranchi", value: "Ranchi" },
  { key: 47, label: "Gwalior", value: "Gwalior" },
  { key: 48, label: "Chandigarh", value: "Chandigarh" },
  { key: 49, label: "Haldwani", value: "Haldwani" },
  { key: 50, label: "Vijayawada", value: "Vijayawada" },
  { key: 51, label: "Jodhpur", value: "Jodhpur" },
  { key: 52, label: "Raipur", value: "Raipur" },
  { key: 53, label: "Kota", value: "Kota" },
  { key: 54, label: "Bhayandar", value: "Bhayandar" },
  { key: 55, label: "Loni", value: "Loni" },
  { key: 56, label: "Ambattur", value: "Ambattur" },
  { key: 57, label: "Salt Lake City", value: "Salt Lake City" },
  { key: 58, label: "Bhatpara", value: "Bhatpara" },
  { key: 59, label: "Kukatpalli", value: "Kukatpalli" },
  { key: 60, label: "Dasarhalli", value: "Dasarhalli" },
  { key: 61, label: "Muzaffarpur", value: "Muzaffarpur" },
  { key: 62, label: "Oulgaret", value: "Oulgaret" },
  { key: 63, label: "New Delhi", value: "New Delhi" },
  { key: 64, label: "Tiruvottiyur", value: "Tiruvottiyur" },
  { key: 65, label: "Puducherry", value: "Puducherry" },
  { key: 66, label: "Byatarayanpur", value: "Byatarayanpur" },
  { key: 67, label: "Pallavaram", value: "Pallavaram" },
  { key: 68, label: "Secunderabad", value: "Secunderabad" },
  { key: 69, label: "Shimla", value: "Shimla" },
  { key: 70, label: "Puri", value: "Puri" },
  { key: 71, label: "Murtazabad", value: "Murtazabad" },
  { key: 72, label: "Shrirampur", value: "Shrirampur" },
  { key: 73, label: "Chandannagar", value: "Chandannagar" },
  { key: 74, label: "Sultampur Mazra", value: "Sultampur Mazra" },
  { key: 75, label: "Krishnanagar", value: "Krishnanagar" },
  { key: 76, label: "Barakpur", value: "Barakpur" },
  { key: 77, label: "Bhalaswa Jahangirpur", value: "Bhalaswa Jahangirpur" },
  { key: 78, label: "Nangloi Jat", value: "Nangloi Jat" },
  { key: 79, label: "Balasore", value: "Balasore" },
  { key: 80, label: "Dalupura", value: "Dalupura" },
  { key: 81, label: "Yelahanka", value: "Yelahanka" },
  { key: 82, label: "Titagarh", value: "Titagarh" },
  { key: 83, label: "Dam Dam", value: "Dam Dam" },
  { key: 84, label: "Bansbaria", value: "Bansbaria" },
  { key: 85, label: "Madhavaram", value: "Madhavaram" },
  { key: 86, label: "Abbigeri", value: "Abbigeri" },
  { key: 87, label: "Baj Baj", value: "Baj Baj" },
  { key: 88, label: "Garhi", value: "Garhi" },
  { key: 89, label: "Mirpeta", value: "Mirpeta" },
  { key: 90, label: "Nerkunram", value: "Nerkunram" },
  { key: 91, label: "Kendrapara", value: "Kendrapara" },
  { key: 92, label: "Sijua", value: "Sijua" },
  { key: 93, label: "Manali", value: "Manali" },
  { key: 94, label: "Kankuria", value: "Kankuria" },
  { key: 95, label: "Chakapara", value: "Chakapara" },
  { key: 96, label: "Pappakurichchi", value: "Pappakurichchi" },
  { key: 97, label: "Herohalli", value: "Herohalli" },
  { key: 98, label: "Madipakkam", value: "Madipakkam" },
  { key: 99, label: "Sabalpur", value: "Sabalpur" },
  { key: 100, label: "Bauria", value: "Bauria" },
  { key: 101, label: "Salua", value: "Salua" },
  { key: 102, label: "Chik Bnavar", value: "Chik Bnavar" },
  { key: 103, label: "Jalhalli", value: "Jalhalli" },
  { key: 104, label: "Chinnasekkadu", value: "Chinnasekkadu" },
  { key: 105, label: "Jethuli", value: "Jethuli" },
  { key: 106, label: "Nagtala", value: "Nagtala" },
  { key: 107, label: "Pakri", value: "Pakri" },
  { key: 108, label: "Hunasamaranhalli", value: "Hunasamaranhalli" },
  { key: 109, label: "Hesarghatta", value: "Hesarghatta" },
  { key: 110, label: "Bommayapalaiyam", value: "Bommayapalaiyam" },
  { key: 111, label: "Gundur", value: "Gundur" },
  { key: 112, label: "Punadih", value: "Punadih" },
  { key: 113, label: "Hariladih", value: "Hariladih" },
  { key: 114, label: "Alawalpur", value: "Alawalpur" },
  { key: 115, label: "Madnaikanhalli", value: "Madnaikanhalli" },
  { key: 116, label: "Bagalur", value: "Bagalur" },
  { key: 117, label: "Kadiganahalli", value: "Kadiganahalli" },
  { key: 118, label: "Khanpur Zabti", value: "Khanpur Zabti" },
  { key: 119, label: "Mahuli", value: "Mahuli" },
  { key: 120, label: "Zeyadah Kot", value: "Zeyadah Kot" },
  { key: 121, label: "Arshakunti", value: "Arshakunti" },
  { key: 122, label: "Mirchi", value: "Mirchi" },
  { key: 123, label: "Sonudih", value: "Sonudih" },
  { key: 124, label: "Bayandhalli", value: "Bayandhalli" },
  { key: 125, label: "Sondekoppa", value: "Sondekoppa" },
  { key: 126, label: "Babura", value: "Babura" },
  { key: 127, label: "Madavar", value: "Madavar" },
  { key: 128, label: "Kadabgeri", value: "Kadabgeri" },
  { key: 129, label: "Nanmangalam", value: "Nanmangalam" },
  { key: 130, label: "Taliganja", value: "Taliganja" },
  { key: 131, label: "Tarchha", value: "Tarchha" },
  { key: 132, label: "Belgharia", value: "Belgharia" },
  { key: 133, label: "Kammanhalli", value: "Kammanhalli" },
  { key: 134, label: "Ambapuram", value: "Ambapuram" },
  { key: 135, label: "Sonnappanhalli", value: "Sonnappanhalli" },
  { key: 136, label: "Kedihati", value: "Kedihati" },
  { key: 137, label: "Doddajivanahalli", value: "Doddajivanahalli" },
  { key: 138, label: "Simli Murarpur", value: "Simli Murarpur" },
  { key: 139, label: "Sonawan", value: "Sonawan" },
  { key: 140, label: "Devanandapur", value: "Devanandapur" },
  { key: 141, label: "Tribeni", value: "Tribeni" },
  { key: 142, label: "Huttanhalli", value: "Huttanhalli" },
  { key: 143, label: "Nathupur", value: "Nathupur" },
  { key: 144, label: "Bali", value: "Bali" },
  { key: 145, label: "Vajarhalli", value: "Vajarhalli" },
  { key: 146, label: "Alija Kotla", value: "Alija Kotla" },
  { key: 147, label: "Saino", value: "Saino" },
  { key: 148, label: "Shekhpura", value: "Shekhpura" },
  { key: 149, label: "Cachoha", value: "Cachoha" },
  { key: 150, label: "Andheri", value: "Andheri" },
  { key: 151, label: "Narayanpur Kola", value: "Narayanpur Kola" },
  { key: 152, label: "Gyan Chak", value: "Gyan Chak" },
  { key: 153, label: "Kasgatpur", value: "Kasgatpur" },
  { key: 154, label: "Kitanelli", value: "Kitanelli" },
  { key: 155, label: "Harchandi", value: "Harchandi" },
  { key: 156, label: "Santoshpur", value: "Santoshpur" },
  { key: 157, label: "Bendravadi", value: "Bendravadi" },
  { key: 158, label: "Kodagihalli", value: "Kodagihalli" },
  { key: 159, label: "Harna Buzurg", value: "Harna Buzurg" },
  { key: 160, label: "Mailanhalli", value: "Mailanhalli" },
  { key: 161, label: "Sultampur", value: "Sultampur" },
  { key: 162, label: "Adakimaranhalli", value: "Adakimaranhalli" },
  { key: 163, label: "Delhi NCR", value: "Delhi NCR" },
  { key: 164, label: "Gurugram", value: "Gurugram" },
  { key: 165, label: "Noida", value: "Noida" },
  
];

export const stateOptions = [
  {
    key: 1,
    label: "Andaman and Nicobar Islands",
    value: "Andaman and Nicobar Islands",
  },
  {key: 2, label: "Andhra Pradesh", value: "Andhra Pradesh"},
  {key: 3, label: "Arunachal Pradesh", value: "Arunachal Pradesh"},
  {key: 4, label: "Assam", value: "Assam"},
  {key: 5, label: "Bihar", value: "Bihar"},
  {key: 6, label: "Chandigarh", value: "Chandigarh"},
  {key: 7, label: "Chhattisgarh", value: "Chhattisgarh"},
  {
    key: 8,
    label: "Dadra and Nagar Haveli and Daman and Diu",
    value: "Dadra and Nagar Haveli and Daman and Diu",
  },
  {key: 9, label: "Delhi", value: "Delhi"},
  {key: 10, label: "Goa", value: "Goa"},
  {key: 11, label: "Gujarat", value: "Gujarat"},
  {key: 12, label: "Haryana", value: "Haryana"},
  {key: 13, label: "Himachal Pradesh", value: "Himachal Pradesh"},
  {key: 14, label: "Hyderabad", value: "Hyderabad"},
  {key: 15, label: "Jammu and Kashmir", value: "Jammu and Kashmir"},
  {key: 16, label: "Jharkhand", value: "Jharkhand"},
  {key: 17, label: "Karnataka", value: "Karnataka"},
  {key: 18, label: "Kerala", value: "Kerala"},
  {key: 19, label: "Ladakh", value: "Ladakh"},
  {key: 20, label: "Lakshadweep", value: "Lakshadweep"},
  {key: 21, label: "Madhya Pradesh", value: "Madhya Pradesh"},
  {key: 22, label: "Maharashtra", value: "Maharashtra"},
  {key: 23, label: "Manipur", value: "Manipur"},
  {key: 24, label: "Meghalaya", value: "Meghalaya"},
  {key: 25, label: "Mizoram", value: "Mizoram"},
  {key: 26, label: "Nagaland", value: "Nagaland"},
  {key: 27, label: "Odisha", value: "Odisha"},
  {key: 28, label: "Puducherry", value: "Puducherry"},
  {key: 29, label: "Punjab", value: "Punjab"},
  {key: 30, label: "Rajasthan", value: "Rajasthan"},
  {key: 31, label: "Sikkim", value: "Sikkim"},
  {key: 32, label: "Tamil Nadu", value: "Tamil Nadu"},
  {key: 33, label: "Telangana", value: "Telangana"},
  {key: 34, label: "Tripura", value: "Tripura"},
  {key: 35, label: "Uttar Pradesh", value: "Uttar Pradesh"},
  {key: 36, label: "Uttarakhand", value: "Uttarakhand"},
  {key: 37, label: "West Bengal", value: "West Bengal"},
];



